arb-dir: lib/l10n
template-arb-file: app_ru_RU.arb
output-localization-file: app_localizations.dart
output-class: AppLocalizations
preferred-supported-locales: [ru]
use-deferred-loading: false 
untranslated-messages-file: untranslated.json 