const List<String> cardFilenames = [
  'the emperor.jpg',
  'the fool.jpg',
  'the hierophant.jpg',
  'the high priestess.jpg',
  'the magician.jpg',
  'the empress.jpg',
  'strength.jpg',
  'the chariot.jpg',
  'the lovers.jpg',
  'the hermit.jpg',
  'death.jpg',
  'judgement.jpg',
  'justice.jpg',
  'temperance.jpg',
  'the devil.jpg',
  'the hanged man.jpg',
  'the moon.jpg',
  'the star.jpg',
  'the sun.jpg',
  'the tower.jpg',
  'the world.jpg',
  'wheel of fortune.jpg',
  'ace of wands.jpg',
  '2 of wands.jpg',
  '3 of wands.jpg',
  '4 of wands.jpg',
  '5 of wands.jpg',
  '6 of wands.jpg',
  '7 of wands.jpg',
  '8 of wands.jpg',
  '9 of wands.jpg',
  '10 of wands.jpg',
  'king of wands.jpg',
  'knight of wands.jpg',
  'page of wands.jpg',
  'queen of wands.jpg',
  'ace of cups.jpg',
  '2 of cups.jpg',
  '3 of cups.jpg',
  '4 of cups.jpg',
  '5 of cups.jpg',
  '6 of cups.jpg',
  '7 of cups.jpg',
  '8 of cups.jpg',
  '9 of cups.jpg',
  '10 of cups.jpg',
  'king of cups.jpg',
  'knight of cups.jpg',
  'page of cups.jpg',
  'queen of cups.jpg',
  'ace of swords.jpg',
  '2 of swords.jpg',
  '3 of swords.jpg',
  '4 of swords.jpg',
  '5 of swords.jpg',
  '6 of swords.jpg',
  '7 of swords.jpg',
  '8 of swords.jpg',
  '9 of swords.jpg',
  '10 of swords.jpg',
  'king of swords.jpg',
  'knight of swords.jpg',
  'page of swords.jpg',
  'queen of swords.jpg',
  'ace of pentacles.jpg',
  '2 of pentacles.jpg',
  '3 of pentacles.jpg',
  '4 of pentacles.jpg',
  '5 of pentacles.jpg',
  '6 of pentacles.jpg',
  '7 of pentacles.jpg',
  '8 of pentacles.jpg',
  '9 of pentacles.jpg',
  '10 of pentacles.jpg',
  'king of pentacles.jpg',
  'knight of pentacles.jpg',
  'page of pentacles.jpg',
  'queen of pentacles.jpg',
]; 