name: Build CocoaPods for iOS

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build-pods:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Ruby and CocoaPods
        run: |
          sudo gem install cocoapods

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.0'

      - name: Install Flutter dependencies
        run: flutter pub get

      - name: Install CocoaPods dependencies
        run: |
          cd ios
          pod install --verbose

      - name: Archive Pods
        run: |
          cd ios
          tar -czf Pods-and-PodfileLock.tar.gz Pods Podfile.lock

      - name: Upload Pods artifact
        uses: actions/upload-artifact@v3
        with:
          name: Pods-and-PodfileLock
          path: ios/Pods-and-PodfileLock.tar.gz 